on:
  push:
    branches:
      - 'main'
    paths:
      - 'resume/**'
jobs:
  push-content:
    runs-on: ubuntu-latest
    name: Push the contents of the repo to a Oracle Object Storage bucket
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Install dependencies
        run: sudo apt install python3-testresources
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Sync files to bucket
        uses: oracle-actions/run-oci-cli-command@v1.1
        id: sync-files
        with:
          command: 'os object sync -bn resume --src-dir resume --content-type text'
          silent: true
